bundler_args: --retry=3 --jobs=3
cache: bundler
language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2.1
  - 2.2.0
  - jruby-head
  - jruby-9.0.0.0.pre1
  - rbx-2
  - ruby-head
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
matrix:
  allow_failures:
    - rvm: 2.2.0
    - rvm: jruby-head
    - rvm: jruby-9.0.0.0.pre1
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
notifications:
  slack:
    secure: wZ1UPEcH/Zf/wSPvpR1q76vpUQvAEGuwR5500ML8C+shW7PedvuSZaiZYAOZxhyD17RXzXYroON0ArEk3NUcKD8supPzYjUWzCeWDIFaYxEb7dOm7tpRBf4GuQ/oy8HGsBi947ZTX3WytGWZU0q0aRu2EirPcoY05vzley/hYTI=
